% KDTREE_LOAD loads a kd-tree from a binary file
%
% Added by Pablo Sala, November 25, 2008
%
% SYNTAX
% kdtree_load(filename)
%
% INPUT PARAMETERS
%   filename: name of file previously generated by a call to KDTREE_SAVE
%
% DESCRIPTION
% Loads a kd-tree from a file that was previously generated by a call to
% KDTREE_SAVE.
% 
% See also:
% KDTREE_SAVE

% Copyright (c) 2008 Andrea Tagliasacchi
% All Rights Reserved
% email: ata2@cs.sfu.ca 
% $Revision: 1.0$  Created on: 2008/09/15
